title: Welcome to MISL-SJTU
author: MISL-SJTU
email: cascades@sjtu.edu.cn
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  MISL-SJTU offical github account, powered by jekyll

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  MISL-SJTU # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
